### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by ghost** [Zubenna/youtube-clone#2]
Great job! we have some notes:

-Make a read.me file, you can use the template Microverse provides.
-Don't use comments on your code.
-Try to fix the horizontal scroll, maybe giving the navbar a smaller width.
-Make a description of the project on the pull request.
-Store images locally.
-Try to style more on the CSS file instead of HTML.
-Clean blank spaces.
-More descriptive commit messages.
-Use images instead of SVG.
-The share button must be a button.
-Try to use more elements, not just H.

Keep the good work.

**Comment by Zubenna** [comment]
Suggestions has been implemented.
