### ISSUE TITLE
Morning session 26/Feb/2020: Code review

### ISSUE THREAD

**Issue by alvarorf** [Zubenna/youtube-clone#3]
The project looks great, the only things we would add are:
1) Maybe use a different font for the website.
2) The Readme file could be improved.
3) Perhaps use comments to divide sections of the code.
4) Should start using lint for the second project.
5) Maybe divide the styling for different sections in different css files.

Congrats for getting the project approved and keep up the good work!

**Comment by Zubenna** [comment]
Noted.
